name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev-build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: DbUp
      run: |
        docker build . --file DbUp/Dockerfile -t dbup
        docker run dbup '${{ secrets.PASSWORD_MANAGER_DB }}'
    
    - name: docker build and push
      run: |
        docker build . --file WebApp/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/password-manager-server:dev
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/password-manager-server:dev
        docker push ${{ secrets.PI_REGISTRY_SERVER }}/password-manager-server:dev
