name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  dev-build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: private docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.PI_REGISTRY_SERVER }}
        username: ${{ secrets.PI_REGISTRY_SERVER_USER }}
        password: ${{ secrets.PI_REGISTRY_SERVER_PASSWORD }}
        
    - name: DbUp
      run: |
        docker build . --file DbUp/Dockerfile -t dbup
        docker run dbup '${{ secrets.PASSWORD_MANAGER_DB }}'
    
    - name: docker build and push
      run: |
        docker build . --file WebApi/Dockerfile \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/password-manager-server:dev \
          -t ${{ secrets.PI_REGISTRY_SERVER }}/password-manager-server
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/password-manager-server:dev
        docker push ${{ secrets.PI_REGISTRY_SERVER }}/password-manager-server

    - name: webhook
      run: |
        curl --fail -X POST -H 'Content-Type: application/json' \
        -d '{
              "image": "${{ secrets.PI_REGISTRY_SERVER }}/password-manager-server",
              "env_variables": {
                "PasswordManagerDb": "${{ secrets.PASSWORD_MANAGER_DB }}"
              }
            }' \
        -u ${{ secrets.WEBHOOK_USER }}:${{ secrets.WEBHOOK_PASSWORD }} \
        ${{ secrets.WEBHOOK_URL }}
